### PR TITLE
feat(github): add milestone percentages

### PR DESCRIPTION
**Pull request by wopian**
Implements #357 

Division by 0 is handled and follows GitHub by treating no issues as 0%. Percentages are floored to the nearest integer (e.g 94%)

### CODE REVIEW

**Comment by amio** [comment]
PS, @wopian what do you think about an actual bar? built with `█▉▊▋▌▍▎▏` and `\u0020`(spaces):

**Comment by styfle** [comment]
The actual bar looks really strange. I don't think it would be clear what it means.

I think it would be best to show a color and a percentage like code coverage.

image

image

**Comment by amio** [comment]
Plus, I forgot there's another rule, __the badge color should represent `status`, not other info__

**Comment by wopian** [comment]
image

image

**Comment by amio** [comment]
Sorry I didn't make it clear 😂

I agree with @styfle 's opinion that __"a milestone is similar to test coverage -- its all the issues you have to fix to ship the milestone"__, and with another thought supporting it too: __"the badge color should represent `status`, the percent, not the implicit onSchedule"__.

So let's keep your original implementation, @wopian sorry for the extra works 🙏

**Comment by amio** [comment]
@wopian Can you revert last change? then we are good to go!

**Comment by amio** [comment]
@wopian Thanks!

**Comment by tunnckoCore** [comment]
Sweeet!

**Pull request merged**
