### PR TITLE
Support other providers for LGTM badge

### LINKED ISSUE #356: Support bitbucket/gitlab in LGTM badges
Currently, there is support only for GitHub repositories. However, GitLab and BitBucket repos exist with the prefix of /gl/ and /b/ instead of GitHub's /g/ on LGTM's API, so this should be a customisation option.

Example bitbucket LGTM: https://lgtm.com/projects/b/wegtam/bitbucket-youtrack-broker/?mode=list
Example gitlab LGTM: https://lgtm.com/projects/gl/nekokatt/hikari/?mode=list

### PR DESCRIPTION
**Pull request by vladimyr**
This closes #356 

@nekokatt Are you ok with using your work as badge example?

### CODE REVIEW

**Comment by vladimyr** [comment]
> I think support for `github|bitbucket|gitlab` would be valuable too.

Actually I've changed it to support `g|github|bitbucket|gitlab` exclusively because badgen doesn't support short names elsewhere and `g` is added just to keep compatibility with existing badges.

**Comment by tunnckoCore** [comment]
True :)

**Comment by nekokatt** [comment]
Go for it :-)

**Comment by amio** [comment]
@vladimyr Thanks!

**Pull request merged**
